language: c

os:
  - linux
  - osx

compiler:
  - gcc

branches:
  only:
    - master

before_install:
  - |
    if [ $TRAVIS_OS_NAME = linux ]; then
      sudo apt-get purge cmake
      sudo apt-key update
      sudo apt-get update
      sudo apt-get -y -f install gfortran python python3 cmake
    fi
  - |
    if [ $TRAVIS_OS_NAME = osx ]; then
      brew update && brew install gcc
    fi

install:
  - pip install sphinx sphinx_rtd_theme

script:
  - cd docs && make html && cd ..
  - cd src
  - make all
  - make debug
  # - cd fehmpytests/ && python fehmpytests.py ../src/xfehm_v3.3.1

after_success:
  - echo FEHM compilation successful
