"""
A collection of useful functions for manipulating mesh files generated by LaGriT, PyLaGriT, etc.
"""
import os
import shutil

__author__ = "John P. Ortiz"

def zone_to_zonn(zone_filename):
    '''
    Creates an FEHM .zone file from a .zonn file with the same
    prefix.
    (e.g. mesh_material.zone --> mesh_material.zonn)
    '''
    prefix,ext = os.path.splitext(zone_filename)
    outf = prefix+'.zonn'
    shutil.copyfile(zone_filename, outf)
    with open(outf, 'r') as f:
        lines = f.readlines()
    lines[0] = 'zonn\n'
    with open(outf, 'w') as f:
        f.writelines(lines)

