      subroutine releasemem
!***********************************************************************
!  Copyright, 1993, 2004,  The  Regents of the University of California.
!  This program was prepared by the Regents of the University of 
!  California at Los Alamos National Laboratory (the University) under  
!  contract No. W-7405-ENG-36 with the U.S. Department of Energy (DOE). 
!  All rights in the program are reserved by the DOE and the University. 
!  Permission is granted to the public to copy and use this software 
!  without charge, provided that this Notice and any statement of 
!  authorship are reproduced on all copies. Neither the U.S. Government 
!  nor the University makes any warranty, express or implied, or 
!  assumes any liability or responsibility for the use of this software.
!***********************************************************************
!D1
!D1 PURPOSE
!D1
!D1 Deallocate memory of dynamic variable arrays.
!D1 
!***********************************************************************
!D2
!D2 REVISION HISTORY
!D2
!D2 FEHM Version 2.10 [10086-STN-2.10-00]
!D2
!D2 Initial implementation: 15-FEB-00, Programmer: B. Robinson
!D2
!D2 $Log:   /pvcs.config/fehm90/src/releasemem.f_a  $
!D2
!D2    Rev 2.5   06 Jan 2004 10:43:48   pvcs
!D2 FEHM Version 2.21, STN 10086-2.21-00, Qualified October 2003
!D2
!D2    Rev 2.4   29 Jan 2003 09:13:32   pvcs
!D2 FEHM Version 2.20, STN 10086-2.20-00
!D2 
!D2    Rev 2.3   14 Nov 2001 13:03:58   pvcs
!D2 FEHM Version 2.12, STN 10086-2.12-00
!D2 Update the GoldSim / FEHM interface
!D2 
!D2    Rev 2.2   06 Jun 2001 13:36:36   pvcs
!D2 FEHM Version 2.11, STN 10086-2.11-00
!D2 
!D2    Rev 2.2   06 Jun 2001 08:26:24   pvcs
!D2 Update for extended dispersion tensor model
!D2 
!D2    Rev 2.1   30 Nov 2000 12:07:04   pvcs
!D2 FEHM Version 2.10, STN 10086-2.10-00
!D2 
!***********************************************************************
!D3
!D3 INTERFACES
!D3
!D3 None
!D3
!***********************************************************************
!D4
!D4 GLOBAL OBJECTS
!D4
!D4 Global Constants
!D4
!D4   None
!D4
!D4 Global Types
!D4
!D4   None
!D4
!***********************************************************************
!D8
!D8 SPECIAL COMMENTS
!D8
!D8 This routine is a general purpose routine necessary with dynamic
!D8 memory allocation.
!D8
!***********************************************************************
!D9
!D9 REQUIREMENTS TRACEABILITY
!D9
!D9 Not Applicable.  See special comments. 
!D9
!***********************************************************************
!DA
!DA REFERENCES
!DA
!DA None
!DA
!***********************************************************************

      use comflow
      use combi
      use comchem
      use comci
      use comdi
      use comei
      use comfi
      use comgi
      use comhi
      use comii
      use comji
      use comrxnb
      use comrxni
      use davidi
      use comcouple
      use compart
      use comzeoli
      use comdti
      use comai
      use comsptr
      use compfrac
      use comrtd
      use comsk
      use comuserc
      implicit none

      if(allocated(igdpm)) deallocate(igdpm)
      if(allocated(num_particles)) deallocate(num_particles)
c bhl_12/8/05
      if(allocated(num_part_mem)) deallocate(num_part_mem)
      if(allocated(cfraction)) deallocate(cfraction)
c bhl_12/8/05
      if(allocated(num_exit)) deallocate(num_exit)
      if(allocated(ori)) deallocate(ori)
      if(allocated(obj)) deallocate(obj)
      if(allocated(kfact)) deallocate(kfact)
      if(allocated(trak_type)) deallocate(trak_type)
      if(allocated(timeleft)) deallocate(timeleft)
      if(allocated(box)) deallocate(box)
      if(allocated(start_time)) deallocate(start_time)
      if(allocated(frac_done)) deallocate(frac_done)
      if(allocated(theta)) deallocate(theta)
      if(allocated(flow_ot)) deallocate(flow_ot)
      if(allocated(flow_ottot)) deallocate(flow_ottot)
      if(allocated(Rf)) deallocate(Rf)
      if(allocated(mass)) deallocate(mass)
      if(allocated(pconc)) deallocate(pconc)
      if(allocated(kd))   deallocate(kd)
      if(allocated(rd_frac))   deallocate(rd_frac)
      if(allocated(kcoll))   deallocate(kcoll)
      if(allocated(rcoll))   deallocate(rcoll)
      if(allocated(fcoll))   deallocate(fcoll)
      if(allocated(matrix_por))   deallocate(matrix_por)
      if(allocated(aperture))   deallocate(aperture)
      if(allocated(gamma_afm))   deallocate(gamma_afm)
      if(allocated(sresidual))   deallocate(sresidual)
      if(allocated(dispflag))   deallocate(dispflag)
      if(allocated(diffflag))   deallocate(diffflag)
      if(allocated(sud_frind))   deallocate(sud_frind)
      if(allocated(sizes)) deallocate(sizes)
      if(allocated(probsize)) deallocate(probsize)
      if(allocated(porsize)) deallocate(porsize)
      if(allocated(vg_poresize)) deallocate(vg_poresize)
      if(allocated(partsize)) deallocate(partsize)
      if(allocated(diffmfl)) deallocate(diffmfl)
      if(allocated(dispersivity1)) deallocate(dispersivity1)
      if(allocated(dispersivity2)) deallocate(dispersivity2)
      if(allocated(dispersivity3)) deallocate(dispersivity3)
      if(allocated(dispersivity4)) deallocate(dispersivity4)
      if(allocated(dispersivity6)) deallocate(dispersivity6)
      if(allocated(dispersivity7)) deallocate(dispersivity7)
      if(allocated(dispersivity8)) deallocate(dispersivity8)
      if(allocated(vratio)) deallocate(vratio)
      if(allocated(divdwt)) deallocate(divdwt)
      if(allocated(gradd)) deallocate(gradd)
      if(allocated(tprpflag)) deallocate(tprpflag)
      if(allocated(zbtc)) deallocate(zbtc)
      if(allocated(izonebtc)) deallocate(izonebtc)
      if(allocated(totalpart)) deallocate(totalpart)
      if(allocated(totalpart_ret)) deallocate(totalpart_ret)
      if(allocated(totlast)) deallocate(totlast)
      if(allocated(totlast_ret)) deallocate(totlast_ret)
      if(allocated(ttbtc)) deallocate(ttbtc)
      if(allocated(omega_partial)) deallocate(omega_partial)
      if(allocated(sigma_partial)) deallocate(sigma_partial)
      if(allocated(ddx)) deallocate(ddx)
      if(allocated(ddy)) deallocate(ddy)
      if(allocated(ddz)) deallocate(ddz)
      if(allocated(ggg)) deallocate(ggg)
      if(allocated(corn)) deallocate(corn)
      if(allocated(ddxv)) deallocate(ddxv)
      if(allocated(vx1)) deallocate(vx1)
      if(allocated(axv)) deallocate(axv)
      if(allocated(x1)) deallocate(x1)
      if(allocated(x2)) deallocate(x2)
      if(allocated(x3)) deallocate(x3)
      if(allocated(vx1bv)) deallocate(vx1bv)
      if(allocated(vx2bv)) deallocate(vx2bv)
      if(allocated(dtx)) deallocate(dtx)
      if(allocated(x_new)) deallocate(x_new)
      if(allocated(ddyv)) deallocate(ddyv)
      if(allocated(vy1)) deallocate(vy1)
      if(allocated(ayv)) deallocate(ayv)
      if(allocated(y1)) deallocate(y1)
      if(allocated(y2)) deallocate(y2)
      if(allocated(y3)) deallocate(y3)
      if(allocated(vy1bv)) deallocate(vy1bv)
      if(allocated(vy2bv)) deallocate(vy2bv)
      if(allocated(dty)) deallocate(dty)
      if(allocated(y_new)) deallocate(y_new)
      if(allocated(ddzv)) deallocate(ddzv)
      if(allocated(vz1)) deallocate(vz1)
      if(allocated(azv)) deallocate(azv)
      if(allocated(z1)) deallocate(z1)
      if(allocated(z2)) deallocate(z2)
      if(allocated(z3)) deallocate(z3)
      if(allocated(vz1bv)) deallocate(vz1bv)
      if(allocated(vz2bv)) deallocate(vz2bv)
      if(allocated(dtz)) deallocate(dtz)
      if(allocated(z_new)) deallocate(z_new)
      if(allocated(tt)) deallocate(tt)
      if(allocated(dt)) deallocate(dt)
      if(allocated(x61)) deallocate(x61)
      if(allocated(axyzm)) deallocate(axyzm)
      if(allocated(ttt)) deallocate(ttt)
      if(allocated(ttp1)) deallocate(ttp1)
      if(allocated(ioutt)) deallocate(ioutt)
      if(allocated(istop)) deallocate(istop)
      if(allocated(ijkv)) deallocate(ijkv)
      if(allocated(exit_node)) deallocate(exit_node)
      if(allocated(ic_new)) deallocate(ic_new)
      if(allocated(irray)) deallocate(irray)
      if(allocated(divd_omr)) deallocate(divd_omr)
      if(allocated(dpordx_omr)) deallocate(dpordx_omr)
      if(allocated(ijkvs)) deallocate(ijkvs)
      if(allocated(xo)) deallocate(xo)
      if(allocated(yo)) deallocate(yo)
      if(allocated(zo)) deallocate(zo)
      if(allocated(ttpo)) deallocate(ttpo)
      if(allocated(ijkvss)) deallocate(ijkvss)
      if(allocated(vx)) deallocate(vx)
      if(allocated(vy)) deallocate(vy)
      if(allocated(vz)) deallocate(vz)
      if(allocated(edtmax)) deallocate(edtmax)
      if(allocated(npt)) deallocate(npt)
      if(allocated(oldnode)) deallocate(oldnode)
      if(allocated(oldnode_rand)) deallocate(oldnode_rand)
      if(allocated(oldnode2)) deallocate(oldnode2)
      if(allocated(count_steps)) deallocate(count_steps)
      if(allocated(part_id)) deallocate(part_id)
      if(allocated(izonef)) deallocate(izonef)
      if(allocated(izonef_itfc)) deallocate(izonef_itfc)
      if(allocated(zone_pair)) deallocate(zone_pair)
      if(allocated(red_factor)) deallocate(red_factor)
      if(allocated(zonec_pair)) deallocate(zonec_pair)
      if(allocated(ftn_factor)) deallocate(ftn_factor)
      if(allocated(filter_flag)) deallocate(filter_flag)
      if(allocated(itfcsize)) deallocate(itfcsize)
      if(allocated(itfcporsize)) deallocate(itfcporsize)
      if(allocated(itfcprobsize)) deallocate(itfcprobsize)
      if(allocated(ka)) deallocate(ka)
      if(allocated(nar)) deallocate(nar)
      if(allocated(nelm)) deallocate(nelm)
      if(allocated(nelmdg)) deallocate(nelmdg)
      if(allocated(sx1)) deallocate(sx1)
      if(allocated(sxs)) deallocate(sxs)
      if(allocated(dnidnj)) deallocate(dnidnj)
      if(allocated(cord)) deallocate(cord)
      if(allocated(dp)) deallocate(dp)
      if(allocated(dr)) deallocate(dr)
      if(allocated(eta)) deallocate(eta)
      if(allocated(exci)) deallocate(exci)
      if(allocated(si)) deallocate(si)
      if(allocated(w)) deallocate(w)
      if(allocated(wp)) deallocate(wp)
      if(allocated(wr)) deallocate(wr)
      if(allocated(wx)) deallocate(wx)
      if(allocated(wxp)) deallocate(wxp)
      if(allocated(wxr)) deallocate(wxr)
      if(allocated(wy)) deallocate(wy)
      if(allocated(wyp)) deallocate(wyp)
      if(allocated(wyr)) deallocate(wyr)
      if(allocated(wz)) deallocate(wz)
      if(allocated(wzp)) deallocate(wzp)
      if(allocated(wzr)) deallocate(wzr)
      if(allocated(xd)) deallocate(xd)
      if(allocated(xt)) deallocate(xt)
      if(allocated(yd)) deallocate(yd)
      if(allocated(yt)) deallocate(yt)
      if(allocated(zd)) deallocate(zd)
      if(allocated(zt)) deallocate(zt)
      if(allocated(izonesubm)) deallocate(izonesubm)
      if(allocated(pcpnt)) deallocate(pcpnt)
      if(allocated(pimm)) deallocate(pimm)
      if(allocated(pvap)) deallocate(pvap)
      if(allocated(cpntprt)) deallocate(cpntprt)
      if(allocated(cplxprt)) deallocate(cplxprt)
      if(allocated(immprt)) deallocate(immprt)
      if(allocated(vapprt)) deallocate(vapprt)
      if(allocated(cpntnam)) deallocate(cpntnam)
      if(allocated(cplxnam)) deallocate(cplxnam)
      if(allocated(immnam)) deallocate(immnam)
      if(allocated(vapnam)) deallocate(vapnam)
      if(allocated(ndconv)) deallocate(ndconv)
      if(allocated(naqsp)) deallocate(naqsp)
      if(allocated(nimsp)) deallocate(nimsp)
      if(allocated(nivsp)) deallocate(nivsp)
      if(allocated(irxnic)) deallocate(irxnic)
      if(allocated(irxnim)) deallocate(irxnim)
      if(allocated(irxniv)) deallocate(irxniv)
      if(allocated(ckeq)) deallocate(ckeq)
      if(allocated(heq)) deallocate(heq)
      if(allocated(spstoic)) deallocate(spstoic)
      if(allocated(cpntgs)) deallocate(cpntgs)
      if(allocated(idrxn)) deallocate(idrxn)
      if(allocated(ifxconc)) deallocate(ifxconc)
      if(allocated(neg_conc_possible)) 
     2     deallocate(neg_conc_possible)
      if(allocated(cpntsv)) deallocate(cpntsv)
      if(allocated(calcderiv)) deallocate(calcderiv)
      if(allocated(ckeqlb)) deallocate(ckeqlb)
      if(allocated(ckmtrn)) deallocate(ckmtrn)
      if(allocated(simmmx)) deallocate(simmmx)
      if(allocated(kfor)) deallocate(kfor)
      if(allocated(krev)) deallocate(krev)
      if(allocated(sticirrv)) deallocate(sticirrv)
      if(allocated(stimirrv)) deallocate(stimirrv)
      if(allocated(stivirrv)) deallocate(stivirrv)
      if(allocated(ckc)) deallocate(ckc)
      if(allocated(cka)) deallocate(cka)
      if(allocated(decay)) deallocate(decay)
      if(allocated(biofac)) deallocate(biofac)
      if(allocated(hfac)) deallocate(hfac)
      if(allocated(carbfac)) deallocate(carbfac)
      if(allocated(ammfac)) deallocate(ammfac)
      if(allocated(phthresh)) deallocate(phthresh)
      if(allocated(qm)) deallocate(qm)
      if(allocated(yield)) deallocate(yield)
      if(allocated(xminit)) deallocate(xminit)
      if(allocated(nbiofrm)) deallocate(nbiofrm)
      if(allocated(icbio)) deallocate(icbio)
      if(allocated(sarea)) deallocate(sarea)
      if(allocated(pdstic)) deallocate(pdstic)
      if(allocated(pd_flag)) deallocate(pd_flag)
      if(allocated(totaq)) deallocate(totaq)
      if(allocated(cpnt)) deallocate(cpnt)
      if(allocated(cplx)) deallocate(cplx)
      if(allocated(rrcplx)) deallocate(rrcplx)
      if(allocated(rrcpnt)) deallocate(rrcpnt)
      if(allocated(rrimm)) deallocate(rrimm)
      if(allocated(rrvap)) deallocate(rrvap)
      if(allocated(drdctaq)) deallocate(drdctaq)
      if(allocated(drdcimm)) deallocate(drdcimm)
      if(allocated(drdcvap)) deallocate(drdcvap)
      if(allocated(drcpnt)) deallocate(drcpnt)
      if(allocated(drimm)) deallocate(drimm)
      if(allocated(drvap)) deallocate(drvap)
      if(allocated(drtaq)) deallocate(drtaq)
      if(allocated(drcplx)) deallocate(drcplx)
      if(allocated(xjac)) deallocate(xjac)
      if(allocated(dxct)) deallocate(dxct)
      if(allocated(resid)) deallocate(resid)
      if(allocated(ipiv)) deallocate(ipiv)
      if(allocated(ipiv2)) deallocate(ipiv2)
      if(allocated(nterms)) deallocate(nterms)
      if(allocated(sclmtx)) deallocate(sclmtx)
      if(allocated(sclfactr)) deallocate(sclfactr)
      if(allocated(rxnon)) deallocate(rxnon)
      if(allocated(temp_model)) deallocate(temp_model)
      if(allocated(temp_model_kin)) deallocate(temp_model_kin)
      if(allocated(tcoeff)) deallocate(tcoeff)
      if(allocated(pcp)) deallocate(pcp)
      if(allocated(deneh)) deallocate(deneh)
      if(allocated(denej)) deallocate(denej)
      if(allocated(eflow)) deallocate(eflow)
      if(allocated(esk)) deallocate(esk)
      if(allocated(pflow)) deallocate(pflow)
      if(allocated(phi)) deallocate(phi)
      if(allocated(pho)) deallocate(pho)
      if(allocated(pnx)) deallocate(pnx)
      if(allocated(pny)) deallocate(pny)
      if(allocated(pnz)) deallocate(pnz)
      if(allocated(ps)) deallocate(ps)
      if(allocated(rlp_fac)) deallocate(rlp_fac)
      if(allocated(ps_trac)) deallocate(ps_trac)
      if(allocated(qh)) deallocate(qh)
      if(allocated(s)) deallocate(s)
      if(allocated(sk)) deallocate(sk)
      if(allocated(so)) deallocate(so)
      if(allocated(t)) deallocate(t)
      if(allocated(cpr)) deallocate(cpr)
      if(allocated(denr)) deallocate(denr)
      if(allocated(denh)) deallocate(denh)
      if(allocated(denj)) deallocate(denj)
      if(allocated(thx)) deallocate(thx)
c gaz debug 112114      
c      if(allocated(dvas)) deallocate(dvas)
      if(allocated(thy)) deallocate(thy)
      if(allocated(thz)) deallocate(thz)
      if(allocated(qflux)) deallocate(qflux)
      if(allocated(qflxm)) deallocate(qflxm)
      if(allocated(to)) deallocate(to)
      if(allocated(vf)) deallocate(vf)
      if(allocated(volume)) deallocate(volume)
      if(allocated(wellim)) deallocate(wellim)
      if(allocated(nskw)) deallocate(nskw)
      if(allocated(nskw2)) deallocate(nskw2)
      if(allocated(a1adfl)) deallocate(a1adfl)
      if(allocated(a1adfv)) deallocate(a1adfv)
      if(allocated(a2adfl)) deallocate(a2adfl)
      if(allocated(a2adfv)) deallocate(a2adfv)
      if(allocated(an)) deallocate(an)
      if(allocated(anl)) deallocate(anl)
      if(allocated(anlo)) deallocate(anlo)
      if(allocated(anv)) deallocate(anv)
      if(allocated(betadfl)) deallocate(betadfl)
      if(allocated(betadfv)) deallocate(betadfv)
      if(allocated(cm)) deallocate(cm)
      if(allocated(cm0)) deallocate(cm0)
      if(allocated(cnsk)) deallocate(cnsk)
      if(allocated(pcnsk)) deallocate(pcnsk)
      if(allocated(henry_model)) deallocate(henry_model)
      if(allocated(hawwa)) deallocate(hawwa)
      if(allocated(a_henry)) deallocate(a_henry)
      if(allocated(dh_henry)) deallocate(dh_henry)
      if(allocated(cp1f)) deallocate(cp1f)
      if(allocated(cp2f)) deallocate(cp2f)
      if(allocated(cp3f)) deallocate(cp3f)
      if(allocated(cp4f)) deallocate(cp4f)
      if(allocated(tclx)) deallocate(tclx)
      if(allocated(tcly)) deallocate(tcly)
      if(allocated(tclz)) deallocate(tclz)
      if(allocated(dench)) deallocate(dench)
      if(allocated(dencj)) deallocate(dencj)
      if(allocated(diffmfv)) deallocate(diffmfv)
      if(allocated(fc)) deallocate(fc)
      if(allocated(flx12l)) deallocate(flx12l)
      if(allocated(flx12v)) deallocate(flx12v)
      if(allocated(qcin)) deallocate(qcin)
      if(allocated(qcout)) deallocate(qcout)
      if(allocated(qcrxn)) deallocate(qcrxn)
      if(allocated(rc)) deallocate(rc)
      if(allocated(rcss)) deallocate(rcss)
      if(allocated(rp1f)) deallocate(rp1f)
      if(allocated(rp2f)) deallocate(rp2f)
      if(allocated(rp3f)) deallocate(rp3f)
      if(allocated(rp4f)) deallocate(rp4f)
      if(allocated(rp5f)) deallocate(rp5f)
      if(allocated(rp6f)) deallocate(rp6f)
      if(allocated(rp7f)) deallocate(rp7f)
      if(allocated(rp8f)) deallocate(rp8f)
      if(allocated(rp9f)) deallocate(rp9f)
      if(allocated(rp10f)) deallocate(rp10f)
      if(allocated(rp11f)) deallocate(rp11f)
      if(allocated(rp12f)) deallocate(rp12f)
      if(allocated(rp13f)) deallocate(rp13f)
      if(allocated(rp14f)) deallocate(rp14f)
      if(allocated(rp15f)) deallocate(rp15f)
      if(allocated(rp16f)) deallocate(rp16f)
      if(allocated(rp17f)) deallocate(rp17f)
      if(allocated(rp18f)) deallocate(rp18f)
      if(allocated(rp19f)) deallocate(rp19f)
      if(allocated(rp20f)) deallocate(rp20f)
      if(allocated(rp21f)) deallocate(rp21f)
      if(allocated(rp22f)) deallocate(rp22f)
      if(allocated(rp23f)) deallocate(rp23f)
      if(allocated(rp24f)) deallocate(rp24f)
      if(allocated(t1sk)) deallocate(t1sk)
      if(allocated(t2sk)) deallocate(t2sk)
      if(allocated(tcvx)) deallocate(tcvx)
      if(allocated(tcvy)) deallocate(tcvy)
      if(allocated(tcvz)) deallocate(tcvz)
      if(allocated(mflagl)) deallocate(mflagl)
      if(allocated(mflagv)) deallocate(mflagv)
      if(allocated(sehdiff)) deallocate(sehdiff)
      if(allocated(sehdiffv)) deallocate(sehdiffv)
!      if(allocated(thetaresid)) deallocate(thetaresid)
!      if(allocated(thetaresidv)) deallocate(thetaresidv)
      if(allocated(vc1f)) deallocate(vc1f)
      if(allocated(vc2f)) deallocate(vc2f)
      if(allocated(vc3f)) deallocate(vc3f)
      if(allocated(vc4f)) deallocate(vc4f)
      if(allocated(vc5f)) deallocate(vc5f)
      if(allocated(vc6f)) deallocate(vc6f)
      if(allocated(vc7f)) deallocate(vc7f)
      if(allocated(vc8f)) deallocate(vc8f)
      if(allocated(iadd)) deallocate(iadd)
      if(allocated(iaddt)) deallocate(iaddt)
      if(allocated(iadsfl)) deallocate(iadsfl)
      if(allocated(iadsfv)) deallocate(iadsfv)
      if(allocated(icapt)) deallocate(icapt)
      if(allocated(icns)) deallocate(icns)
      if(allocated(iflx1)) deallocate(iflx1)
      if(allocated(iflx2)) deallocate(iflx2)
      if(allocated(nflxc)) deallocate(nflxc)
      if(allocated(irlpt)) deallocate(irlpt)
!     permeability scaling for rlp (ZVD 09-Apr-2010)
      if(allocated(xfperm)) deallocate(xfperm)
      if(allocated(yfperm)) deallocate(yfperm)
      if(allocated(zfperm)) deallocate(zfperm)
      if(allocated(ivcn)) deallocate(ivcn)
      if(allocated(ivcon)) deallocate(ivcon)
      if(allocated(phini)) deallocate(phini)
      if(allocated(psini)) deallocate(psini)
      if(allocated(tini)) deallocate(tini)
      if(allocated(amgang)) deallocate(amgang)
      if(allocated(dporp)) deallocate(dporp)
      if(allocated(dport)) deallocate(dport)
      if(allocated(pgangi)) deallocate(pgangi)
!     temperature-dependent porosity
      if(allocated(porTemp1)) deallocate(porTemp1)
      if(allocated(porTemp2)) deallocate(porTemp2)
      if(allocated(porTemp3)) deallocate(porTemp3)
      if(allocated(porTemp4)) deallocate(porTemp4)
****   TENMA   ****
      if(allocated(wgangi)) deallocate(wgangi)
      if(allocated(sgangi)) deallocate(sgangi)
      if(allocated(agangi)) deallocate(agangi)
      if(allocated(tenma_ww)) deallocate(tenma_ww)
      if(allocated(nskw3)) deallocate(nskw3)
****   TENMA   ****
      if(allocated(strgan)) deallocate(strgan)
      if(allocated(alphae)) deallocate(alphae)
      if(allocated(sii)) deallocate(sii)
      if(allocated(sio)) deallocate(sio)
      if(allocated(ices)) deallocate(ices)
      if(allocated(icap)) deallocate(icap)
      if(allocated(ieos)) deallocate(ieos)
      if(allocated(ieos_ch)) deallocate(ieos_ch)
      if(allocated(iieos)) deallocate(iieos)
      if(allocated(iporf)) deallocate(iporf)
      if(allocated(irlp)) deallocate(irlp)
      if(allocated(itrc)) deallocate(itrc)
      if(allocated(itrcdsp)) deallocate(itrcdsp)
      if(allocated(izone_grad)) deallocate(izone_grad)   
      if(allocated(igradf)) deallocate(igradf)       
      if(allocated(cordg)) deallocate(cordg)        
      if(allocated(var0)) deallocate(var0)         
      if(allocated(grad1)) deallocate(grad1)        
      if(allocated(idirg)) deallocate(idirg)        
      if(allocated(izone_grad_nodes))
     2     deallocate(izone_grad_nodes)       
      if(allocated(iirb)) deallocate(iirb)
      if(allocated(irb)) deallocate(irb)
      if(allocated(nopt)) deallocate(nopt)
      if(allocated(npvt)) deallocate(npvt)
      if(allocated(c)) deallocate(c)
      if(allocated(g)) deallocate(g)
      if(allocated(h)) deallocate(h)
      if(allocated(ss)) deallocate(ss)
      if(allocated(y)) deallocate(y)
      if(allocated(pci)) deallocate(pci)
      if(allocated(pcio)) deallocate(pcio)
      if(allocated(qc)) deallocate(qc)
      if(allocated(cnlf)) deallocate(cnlf)
      if(allocated(cnvf)) deallocate(cnvf)
      if(allocated(dcc)) deallocate(dcc)
      if(allocated(dce)) deallocate(dce)
      if(allocated(dclcf)) deallocate(dclcf)
      if(allocated(dclef)) deallocate(dclef)
      if(allocated(dclf)) deallocate(dclf)
      if(allocated(dcp)) deallocate(dcp)
      if(allocated(dcqc)) deallocate(dcqc)
      if(allocated(dcqh)) deallocate(dcqh)
      if(allocated(dcvcf)) deallocate(dcvcf)
      if(allocated(dcvef)) deallocate(dcvef)
      if(allocated(dcvf)) deallocate(dcvf)
      if(allocated(dec)) deallocate(dec)
      if(allocated(delcf)) deallocate(delcf)
      if(allocated(denpch)) deallocate(denpch)
      if(allocated(denpci)) deallocate(denpci)
      if(allocated(denpcj)) deallocate(denpcj)
      if(allocated(deqc)) deallocate(deqc)
      if(allocated(devcf)) deallocate(devcf)
      if(allocated(dglc)) deallocate(dglc)
      if(allocated(dgvc)) deallocate(dgvc)
      if(allocated(dilc)) deallocate(dilc)
      if(allocated(divc)) deallocate(divc)
      if(allocated(dmc)) deallocate(dmc)
      if(allocated(dqc)) deallocate(dqc)
      if(allocated(dtpac)) deallocate(dtpac)
      if(allocated(qng)) deallocate(qng)
      if(allocated(eskc)) deallocate(eskc)
      if(allocated(sici)) deallocate(sici)
      if(allocated(dfee)) deallocate(dfee)
      if(allocated(dfep)) deallocate(dfep)
      if(allocated(dfepc)) deallocate(dfepc)
      if(allocated(dfme)) deallocate(dfme)
      if(allocated(dfmp)) deallocate(dfmp)
      if(allocated(dfmpc)) deallocate(dfmpc)
      if(allocated(dfpce)) deallocate(dfpce)
      if(allocated(dfpcp)) deallocate(dfpcp)
      if(allocated(dfpcpc)) deallocate(dfpcpc)
      if(allocated(a21eef)) deallocate(a21eef)
      if(allocated(a21epf)) deallocate(a21epf)
      if(allocated(a21mef)) deallocate(a21mef)
      if(allocated(a21mpf)) deallocate(a21mpf)
      if(allocated(a32eef)) deallocate(a32eef)
      if(allocated(a32epf)) deallocate(a32epf)
      if(allocated(a32mef)) deallocate(a32mef)
      if(allocated(a32mpf)) deallocate(a32mpf)
      if(allocated(r3ef)) deallocate(r3ef)
      if(allocated(r3mf)) deallocate(r3mf)
      if(allocated(rb2ef)) deallocate(rb2ef)
      if(allocated(rb2mf)) deallocate(rb2mf)
      if(allocated(tb11)) deallocate(tb11)
      if(allocated(tb12)) deallocate(tb12)
      if(allocated(tb21)) deallocate(tb21)
      if(allocated(tb22)) deallocate(tb22)
      if(allocated(volf2)) deallocate(volf2)
      if(allocated(wb11)) deallocate(wb11)
      if(allocated(wb12)) deallocate(wb12)
      if(allocated(wb21)) deallocate(wb21)
      if(allocated(wb22)) deallocate(wb22)
      if(allocated(apuv1)) deallocate(apuv1)
      if(allocated(volf1)) deallocate(volf1)
      if(allocated(cel)) deallocate(cel)
      if(allocated(cev)) deallocate(cev)
      if(allocated(crl)) deallocate(crl)
      if(allocated(crv)) deallocate(crv)
      if(allocated(cvl)) deallocate(cvl)
      if(allocated(cvv)) deallocate(cvv)
      if(allocated(pmax)) deallocate(pmax)
      if(allocated(pmin)) deallocate(pmin)
      if(allocated(tmax)) deallocate(tmax)
      if(allocated(tmin)) deallocate(tmin)
      if(allocated(avgmolwt)) deallocate(avgmolwt)
      if(allocated(dsccl)) deallocate(dsccl)
      if(allocated(dsccv)) deallocate(dsccv)
      if(allocated(scl)) deallocate(scl)
      if(allocated(scv)) deallocate(scv)
      if(allocated(displx)) deallocate(displx)
      if(allocated(disply)) deallocate(disply)
      if(allocated(displz)) deallocate(displz)
      if(allocated(dispvx)) deallocate(dispvx)
      if(allocated(dispvy)) deallocate(dispvy)
      if(allocated(dispvz)) deallocate(dispvz)
      if(allocated(nb)) deallocate(nb)
      if(allocated(nmat)) deallocate(nmat)
      if(allocated(nmatb)) deallocate(nmatb)
      if(allocated(nrhs)) deallocate(nrhs)
      if(allocated(nrhsb)) deallocate(nrhsb)
      if(allocated(nb_sol)) deallocate(nb_sol)
      if(allocated(nmat_sol)) deallocate(nmat_sol)
      if(allocated(nrhs_sol)) deallocate(nrhs_sol)
      if(allocated(nvar_select)) deallocate(nvar_select)
      if(allocated(t1)) deallocate(t1)
      if(allocated(t2)) deallocate(t2)
      if(allocated(t3)) deallocate(t3)
      if(allocated(t4)) deallocate(t4)
      if(allocated(t5)) deallocate(t5)
      if(allocated(t5v)) deallocate(t5v)
      if(allocated(t6)) deallocate(t6)
      if(allocated(t7)) deallocate(t7)
      if(allocated(t8)) deallocate(t8)
      if(allocated(t9)) deallocate(t9)
      if(allocated(t10)) deallocate(t10)
      if(allocated(it8)) deallocate(it8)
      if(allocated(it9)) deallocate(it9)
      if(allocated(it10)) deallocate(it10)
      if(allocated(it11)) deallocate(it11)
      if(allocated(it12)) deallocate(it12)
      if(allocated(upwind_l)) deallocate(upwind_l)
      if(allocated(upwind_v)) deallocate(upwind_v)
      if(allocated(kzeol)) deallocate(kzeol)
      if(allocated(fwater)) deallocate(fwater)
      if(allocated(fwater_old)) deallocate(fwater_old)
      if(allocated(nelm_primary)) deallocate(nelm_primary)
      if(allocated(nelmdg_primary)) deallocate(nelmdg_primary)
      if(allocated(istrw_primary)) deallocate(istrw_primary)
      if(allocated(istrw)) deallocate(istrw)
      if(allocated(istrw_itfc)) deallocate(istrw_itfc)
      if(allocated(istrw_cold)) deallocate(istrw_cold)
      if(allocated(sx_primary)) deallocate(sx_primary)
      if(allocated(sx)) deallocate(sx)
      if(allocated(idzone)) deallocate(idzone)
      if(allocated(node_model)) deallocate(node_model)
      if(allocated(vtotw)) deallocate(vtotw)
      if(allocated(vtotw)) deallocate(vtotco2)
      if(allocated(vtota)) deallocate(vtota)
      if(allocated(vtote)) deallocate(vtote)
      if(allocated(atotd)) deallocate(atotd)
      if(allocated(node_ch_model)) deallocate(node_ch_model)
      if(allocated(node_ch_model_type)) deallocate(node_ch_model)
      if(allocated(time)) deallocate(time)
      if(allocated(time_cycle)) deallocate(time_cycle)
      if(allocated(time_type)) deallocate(time_type)
      if(allocated(qa)) deallocate(qa)
      if(allocated(sourcea)) deallocate(sourcea)
      if(allocated(sourcea_type)) deallocate(sourcea_type)
      if(allocated(sourcef)) deallocate(sourcef)
      if(allocated(sourcef_type)) deallocate(sourcef_type)
      if(allocated(qw)) deallocate(qw)
      if(allocated(qw0)) deallocate(qw0)
      if(allocated(qco2b)) deallocate(qco2b)
      if(allocated(drain)) deallocate(drain)
      if(allocated(drainar)) deallocate(drainar)
      if(allocated(drainar_type)) deallocate(drainar_type)
      if(allocated(sp)) deallocate(sp)
      if(allocated(seepfac)) deallocate(seepfac)
      if(allocated(seepfac_type)) deallocate(seepfac_type)
      if(allocated(sourcew)) deallocate(sourcew)
      if(allocated(sourcew_type)) deallocate(sourcew_type)
      if(allocated(qenth)) deallocate(qenth)
      if(allocated(sourcee)) deallocate(sourcee)
      if(allocated(sourcee_type)) deallocate(sourcee_type)
      if(allocated(enth)) deallocate(enth)
      if(allocated(enthalpy)) deallocate(enthalpy)
      if(allocated(enthalpy_type)) deallocate(enthalpy_type)
      if(allocated(satb)) deallocate(satb)
      if(allocated(saturation)) deallocate(saturation)
      if(allocated(saturation_type)) deallocate(saturation_type)
      if(allocated(tempb)) deallocate(tempb)
      if(allocated(temperature)) deallocate(temperature)
      if(allocated(temperature_type)) deallocate(temperature_type)
      if(allocated(presa)) deallocate(presa)
      if(allocated(pressurea)) deallocate(pressurea)
      if(allocated(pressurea_type)) deallocate(pressurea_type)
      if(allocated(presw)) deallocate(presw)
      if(allocated(pressurew)) deallocate(pressurew)
      if(allocated(pressurew_type)) deallocate(pressurew_type)
      if(allocated(impedance)) deallocate(impedance)
      if(allocated(impedance_type)) deallocate(impedance_type)
      if(allocated(presw_ini)) deallocate(presw_ini)
      if(allocated(pressurew_ini)) deallocate(pressurew_ini)
      if(allocated(pressurew_ini_type)) 
     2     deallocate(pressurew_ini_type)
      if(allocated(presa_ini)) deallocate(presa_ini)
      if(allocated(pressurea_ini)) deallocate(pressurea_ini)
      if(allocated(pressurea_ini_type)) 
     2     deallocate(pressurea_ini_type)
      if(allocated(satb_ini)) deallocate(satb_ini)
      if(allocated(saturation_ini)) deallocate(saturation_ini)
      if(allocated(saturation_ini_type)) 
     2     deallocate(saturation_ini_type)
      if(allocated(tempb_ini)) deallocate(tempb_ini)
      if(allocated(temperature_ini)) deallocate(temperature_ini)
      if(allocated(temperature_ini_type)) 
     2     deallocate(temperature_ini_type)
      if(allocated(timestep)) deallocate(timestep)
      if(allocated(timestep_type)) deallocate(timestep_type)
      if(allocated(bcoef)) deallocate(bcoef)
      if(allocated(bn)) deallocate(bn)
      if(allocated(head)) deallocate(head)
      if(allocated(pconcmax)) deallocate(pconcmax)
      if(allocated(pcount)) deallocate(pcount)
      if(allocated(idcmax)) deallocate(idcmax)
      if(allocated(idcavg)) deallocate(idcavg)
      if(allocated(idflux)) deallocate(idflux)
      if(allocated(insnode)) deallocate(insnode)
      if(allocated(dum_p)) deallocate(dum_p)
      if(allocated(lsport)) deallocate(lsport)
      if(allocated(nsport)) deallocate(nsport)
      if(allocated(nsegs)) deallocate(nsegs)
      if(allocated(aidex)) deallocate(aidex)
      if(allocated(astep)) deallocate(astep)
      if(allocated(nprevd)) deallocate(nprevd)
      if(allocated(ivdt)) deallocate(ivdt)
      if(allocated(tmsport)) deallocate(tmsport)
      if(allocated(confactor)) deallocate(confactor)
      if(allocated(fracflow)) deallocate (fracflow)
      if(allocated(gmol)) deallocate(gmol)
      if(allocated(bconfactor)) deallocate(bconfactor)
      if(allocated(ioconfactor)) deallocate(ioconfactor)
      if(allocated(sumdecayed)) deallocate(sumdecayed)
      if(allocated(newconfactor)) deallocate(newconfactor)
      if(allocated(conftime)) deallocate(conftime)
      if(allocated(p_fraction)) deallocate(p_fraction)
      if(allocated(ptindex)) deallocate(ptindex)
      if(allocated(p)) deallocate(p)
      if(allocated(p_sf)) deallocate(p_sf)
      if(allocated(partconc)) deallocate(partconc)
      if(allocated(nodepconc)) deallocate(nodepconc)
      if(allocated(nump)) deallocate(nump)
      if(allocated(itf_curve)) deallocate(itf_curve)
      if(allocated(wt_curve)) deallocate(wt_curve)
      if(allocated(param1)) deallocate(param1)
      if(allocated(param2)) deallocate(param2)
      if(allocated(param3)) deallocate(param3)
      if(allocated(dtime)) deallocate(dtime)
      if(allocated(conc)) deallocate(conc)
      if(allocated(param_density)) deallocate(param_density)
      if(allocated(izone_surf)) deallocate(izone_surf)
      if(allocated(izone_surf_nodes)) deallocate(izone_surf_nodes)
      if(allocated(iflxz)) deallocate(iflxz)
      if(allocated(izoneflxz)) deallocate(izoneflxz)
      if(allocated(dit)) deallocate(dit)
      if(allocated(itc)) deallocate(itc)
      if(allocated(mdnode)) deallocate(mdnode)
      if(allocated(mdnodes)) deallocate(mdnodes)
      if(allocated(corz)) deallocate(corz)
      if(allocated(fmvf)) deallocate(fmvf)
      if(allocated(dfmvf)) deallocate(dfmvf)
      if(allocated(fmlf)) deallocate(fmlf)
      if(allocated(dfmlf)) deallocate(dfmlf)
      if(allocated(ngdpm_layers)) deallocate(ngdpm_layers)
      if(allocated(vfrac_primary)) deallocate(vfrac_primary)
      if(allocated(gdpm_x)) deallocate(gdpm_x)
      if(allocated(gdpm_vol)) deallocate(gdpm_vol)
      if(allocated(wgt_length)) deallocate(wgt_length)       
      if(allocated(group)) deallocate(group)
      if(allocated(fzero)) deallocate(fzero)
      if(allocated(pos)) deallocate(pos)
      if(allocated(n_couple_species)) deallocate(n_couple_species)
      if(allocated(alphaconl)) deallocate(alphaconl)
      if(allocated(alphaconv)) deallocate(alphaconv)
      if(allocated(sehvell)) deallocate(sehvell)
      if(allocated(sehvelv)) deallocate(sehvelv)
      if(allocated(a_axy)) deallocate(a_axy)
      if(allocated(a_vxy)) deallocate(a_vxy)
      if(allocated(nop)) deallocate(nop)
      if(allocated(a)) deallocate(a)
      if(allocated(bp)) deallocate(bp)
      if(allocated(bigblock)) deallocate(bigblock)
      if(allocated(thic)) deallocate(thic)
      if(allocated(var1)) deallocate(var1)
      if(allocated(var2)) deallocate(var2)
      if(allocated(dvar11)) deallocate(dvar11)
      if(allocated(dvar12)) deallocate(dvar12)
      if(allocated(dvar21)) deallocate(dvar21)
      if(allocated(dvar22)) deallocate(dvar22)
      if(allocated(node_omr)) deallocate(node_omr)
      if(allocated(istep_cases)) deallocate(istep_cases)
      if(allocated(plum)) deallocate(plum)
      if(allocated(izoneplum)) deallocate(izoneplum)
      if(allocated(plumpart)) deallocate(plumpart)
      if(allocated(rolf)) deallocate(rolf)
      if(allocated(dil)) deallocate(dil)
      if(allocated(rovf)) deallocate(rovf)
      if(allocated(div))  deallocate(div)
      if(allocated(denci)) deallocate(denci)
      if(allocated(flux_ts)) deallocate(flux_ts)
      if(allocated(izone_free)) deallocate(izone_free)
      if(allocated(ifreef)) deallocate(ifreef)
      if(allocated(ifree_im_ex)) deallocate(ifree_im_ex)
      if(allocated(t91)) deallocate(t91)
      if(allocated(dfidf)) deallocate(dfidf)
      if(allocated(dfid1f)) deallocate(dfid1f)
      if(allocated(rlzf)) deallocate(rlzf)       
      if(allocated(rlxyf)) deallocate(rlxyf)
      if(allocated(drlxyf)) deallocate(drlxyf)
      if(allocated(izone_free_nodes)) deallocate(izone_free_nodes)
      if(allocated(head12)) deallocate(head12)
      if(allocated(npest)) deallocate(npest)
      if(allocated(time_rtd)) deallocate(time_rtd)
      if(allocated(rtd)) deallocate(rtd)
      if(allocated(time_subdiv)) deallocate(time_subdiv)
      if(allocated(rtd_subdiv)) deallocate(rtd_subdiv)
      if(allocated(capf)) deallocate(capf)
      if(allocated(cumi)) deallocate(cumi)
      if(allocated(sinkint)) deallocate(sinkint)
      if(allocated(oldlist)) deallocate(oldlist)
      if(allocated(newlist)) deallocate(newlist)
      if(allocated(templist)) deallocate(templist)
cHari 01-Nov-06 release arrays for colloid diversity model
      if(allocated(flag_diversity)) deallocate(flag_diversity)
      if(allocated(divs)) deallocate(divs)
      if(allocated(probdiv)) deallocate(probdiv)
      if(allocated(nprobdivs)) deallocate(nprobdivs)
      if(allocated(rcdiv)) deallocate(rcdiv)
      if(allocated(rcoll_div)) deallocate(rcoll_div)
      if(allocated(flag_col_irrev)) deallocate(flag_col_irrev)
      if(allocated(flag_col_daughter)) deallocate(flag_col_daughter)
      if(allocated(mean_rcoll_reve)) deallocate(mean_rcoll_reve)
      if(allocated(reves)) deallocate(reves)
      if(allocated(irrevs)) deallocate(irrevs)
      if(allocated(flag_log)) deallocate(flag_log)
      if(allocated(flag_method)) deallocate(flag_method)
      if(allocated(ret_weight))  deallocate(ret_weight)
      if(allocated(ret_weight_daughter)) deallocate(ret_weight_daughter)
      if(allocated(r_min)) deallocate(r_min)
      if(allocated(r_max)) deallocate(r_max)
      if(allocated(k_rev)) deallocate(k_rev)
      if(allocated(slope_kf)) deallocate(slope_kf)
      if(allocated(cint_kf)) deallocate(cint_kf)
c zvd 29-Feb-2008 arrays for boun permeabilty and userc models
      if(allocated(permx)) deallocate(permx)
      if(allocated(permx_type)) deallocate(permx_type)
      if(allocated(permy)) deallocate(permy)
      if(allocated(permy_type)) deallocate(permy_type)
      if(allocated(permz)) deallocate(permz)
      if(allocated(permz_type)) deallocate(permz_type)
      if(allocated(prodzones)) deallocate(prodzones)
      if(allocated(inflzones)) deallocate(inflzones)
      if(allocated(userconc)) deallocate(userconc)
      if(allocated(userconc3)) deallocate(userconc3)
      if(allocated(usertime)) deallocate(usertime)
      if(allocated(moles_recycle)) deallocate(moles_recycle)
cbhl  6/4/08      
      if(allocated(bconf_sav)) deallocate(bconf_sav)
cbhl  6/4/08      
                            
      return
      end
